spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmdb2
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true

tmdb:
  api:
    key: 49abb62f10dd83123e00079ba3ceac28
    base-url: https://api.themoviedb.org/3
    max-retries: 3
    retry-delay: 1000